# Generated by Django 3.0.2 on 2020-06-11 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=30, unique=True)),
                ('email', models.CharField(default=' ', max_length=100, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default=' ', max_length=30)),
                ('PhoneNo', models.CharField(blank=True, max_length=11, null=True)),
                ('cnic', models.CharField(blank=True, max_length=13, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('NoOfBottles', models.IntegerField(blank=True, default=0, null=True)),
                ('AmountDue', models.IntegerField(blank=True, default=0, null=True)),
                ('MonthlyBill', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.person',),
        ),
    ]
