# Generated by Django 3.0.2 on 2020-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='19 Litre Bottle', max_length=50)),
                ('total', models.IntegerField()),
                ('filled', models.IntegerField()),
                ('distributed', models.IntegerField()),
            ],
        ),
    ]
