# Generated by Django 3.0.7 on 2020-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
