# Generated by Django 3.0.2 on 2020-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
