# Generated by Django 3.0.7 on 2020-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200620_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='receivedBottle',
            field=models.IntegerField(default=0),
        ),
    ]
