# Generated by Django 3.0.2 on 2020-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200613_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
