# Generated by Django 3.0.7 on 2020-06-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_employee_receivedbottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Employee'),
        ),
    ]
