# Generated by Django 3.0.7 on 2020-07-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_schedule_extrabottles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Products')),
            ],
        ),
    ]
