# Generated by Django 3.0.7 on 2020-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_scheduleproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='daily_load',
            field=models.ManyToManyField(to='database.ScheduleProducts'),
        ),
    ]
