# Generated by Django 3.0.2 on 2020-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200613_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
