# Generated by Django 3.0.2 on 2020-06-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_order_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Area'),
        ),
    ]
