# Generated by Django 3.0.7 on 2020-07-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_schedule_daily_load'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleproducts',
            options={'verbose_name': 'Schedule Product'},
        ),
    ]
