# Generated by Django 3.0.2 on 2020-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_person_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('desc', models.TextField()),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='assets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
