# Generated by Django 3.0.2 on 2020-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_person_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='frequecy',
            field=models.CharField(choices=[('1', 'One Time'), ('2', 'Recursive')], default=('1', 'One Time'), max_length=10),
        ),
    ]
