# Generated by Django 3.0.7 on 2020-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200622_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
