# Generated by Django 3.0.2 on 2020-06-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200614_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frequecy',
            new_name='frequency',
        ),
    ]
