# Generated by Django 3.0.2 on 2020-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200622_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avg_weekly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
