# Generated by Django 3.0.7 on 2020-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200702_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tolerance',
            field=models.IntegerField(default=0),
        ),
    ]
