# Generated by Django 3.0.2 on 2020-06-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_person_avg_weekly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='avg_weekly',
            new_name='AverageWeekly',
        ),
    ]
