# Generated by Django 3.0.7 on 2020-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_area_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleModel', models.CharField(max_length=255)),
                ('weightCapacity', models.IntegerField()),
                ('volumeCapacity', models.IntegerField()),
            ],
        ),
    ]
