# Generated by Django 3.0.7 on 2020-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_schedule_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='tolerance',
            field=models.IntegerField(default=0),
        ),
    ]
