# Generated by Django 3.0.7 on 2020-06-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.VehicleType'),
        ),
    ]
