# Generated by Django 3.0.7 on 2020-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_vehicletype_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tolerance',
            field=models.FloatField(default=0),
        ),
    ]
