# Generated by Django 3.0.2 on 2020-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200623_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='AverageWeekly',
        ),
        migrations.AddField(
            model_name='customer',
            name='AverageWeekly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
