# Generated by Django 3.0.2 on 2020-06-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200623_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='NotInArea',
            field=models.BooleanField(default=False),
        ),
    ]
