# Generated by Django 3.0.7 on 2020-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_vehicle_vehiclemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='capacity',
            new_name='volumeCapacity',
        ),
        migrations.AddField(
            model_name='area',
            name='weightCapacity',
            field=models.IntegerField(default=0),
        ),
    ]
