# Generated by Django 3.0.7 on 2020-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200623_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='schedule',
            field=models.ManyToManyField(to='database.Schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='vehicle',
        ),
    ]
