# Generated by Django 3.0.7 on 2020-06-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200623_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='volumeCapacity',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='volumeCapacity',
        ),
    ]
