# Generated by Django 3.0.7 on 2020-06-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200624_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='discounted_price',
        ),
        migrations.CreateModel(
            name='CustomerPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Products')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='discounted_price',
            field=models.ManyToManyField(to='database.CustomerPrices'),
        ),
    ]
