# Generated by Django 3.0.7 on 2020-06-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200624_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='customerprices',
            options={'verbose_name': 'Customer Assigned Price'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='desc',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.ManyToManyField(to='database.OrderDetail'),
        ),
    ]
