# Generated by Django 3.0.2 on 2020-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200614_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='addresses',
        ),
        migrations.AddField(
            model_name='area',
            name='order',
            field=models.ManyToManyField(to='database.Order'),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
