# Generated by Django 3.0.7 on 2020-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200624_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='orderWeight',
            field=models.IntegerField(default=0),
        ),
    ]
