# Generated by Django 3.0.7 on 2020-06-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_area_orderweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='vehicleModel',
            new_name='vehicle_model',
        ),
    ]
