# Generated by Django 3.0.7 on 2020-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20200624_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='orderWeight',
        ),
        migrations.AddField(
            model_name='schedule',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
