# Generated by Django 3.0.7 on 2020-06-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200624_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='vehicle_capacity',
            new_name='day_capacity',
        ),
    ]
