# Generated by Django 3.0.7 on 2020-06-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20200625_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Vehicle'),
        ),
    ]
