# Generated by Django 3.0.7 on 2020-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20200625_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='vehicle',
            new_name='schedule_day',
        ),
    ]
