# Generated by Django 3.0.7 on 2020-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'High')], default=1),
        ),
    ]
