# Generated by Django 3.0.7 on 2020-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_order_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
