# Generated by Django 3.0.7 on 2020-06-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20200626_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Customer')),
                ('NTN', models.IntegerField(blank=True, null=True)),
                ('STRN', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.IntegerField(blank=True, null=True)),
                ('registered_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.customer',),
        ),
        migrations.AddField(
            model_name='customer',
            name='AverageWeekly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='NotInArea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
    ]
