# Generated by Django 3.0.7 on 2020-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20200626_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='weightCapacity',
        ),
        migrations.AlterField(
            model_name='asset',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
