# Generated by Django 3.0.7 on 2020-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200626_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='database.Order'),
        ),
    ]
