# Generated by Django 3.0.7 on 2020-06-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20200626_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Order', unique=True),
        ),
    ]
