# Generated by Django 3.0.2 on 2020-06-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_is_avaiable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_avaiable',
            new_name='is_available',
        ),
    ]
